name: ansi_text
description: Provides a Dart library for styling and formatting terminal text using the ANSI control codes.
version: 1.0.0
repository: https://github.com/drillster/ansi_text

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  drillster_analysis_options:
    git: 
      url: https://github.com/drillster/drillster_analysis_options
      ref: 1.2.1
  test: ^1.25.8
