name: ansi_text
description: A Dart library for styling and formatting terminal text using the ANSI escape codes.
version: 1.0.2
repository: https://github.com/drillster/ansi_text
license: "MIT"

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  test: ^1.25.8
